CREATE TABLE FOURNISSEUR (

NF INTEGER ,
NOM VARCHAR(50) NOT NULL ,
ADR VARCHAR(50) NOT NULL ,

CONSTRAINT pk_fournisseur PRIMARY KEY (NF)
);

INSERT INTO FOURNISSEUR VALUES(1001 , "Bureau Valle" , "Les Sables d Olonne");



SELECT NOM FROM FOURNISSEUR


MINUS


SELECT distinct nOM
from FOURNISSEUR
JOIN reap ON FOURNISSEUR.NF=reap.NF
join produit on reap.np=produit.np
where lib='Lampe'


SELECT NOM FROM FOURNISSEUR

MINUS 

SELECT NOM FROM FOURNISSEUR
JOIN REAP ON NF.FOURNISSEUR = NF.REAP
WHERE date_reap > '02/02/2020'